steps:
  # Step 1: Wait for 5 minutes
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Waiting for 5 minutes before running the build phase..."
        sleep 10

  # Step 2: Install ffmpeg, dependencies, and run annotation script
  - name: 'python:3.8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd annotation-pipeline
        apt-get update -y
        apt-get install -y ffmpeg libsm6 libxext6 libxrender-dev libgomp1 -qq || echo "Package installation completed with warnings"
        pip install -r requirements.txt
        python3 annotations.py

  # Step 3: Post-build - check directories
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd annotation-pipeline
        echo "Checking predict/ directory..."
        ls -R predict/ || echo "predict/ directory is empty"
        echo "Checking frames/ directory..."
        ls -R frames/ || echo "frames/ directory is empty"

# Timeout for the build
timeout: '1800s'

# Options
options:
  logging: CLOUD_LOGGING_ONLY


# Step 4: Store artifacts in GCS bucket
artifacts:
  objects:
    location: 'gs://annotations123/artifacts/${BUILD_ID}/'
    paths:
      - 'annotation-pipeline/frames/**'
      - 'annotation-pipeline/predict/**'
      - 'annotation-pipeline/inspection.csv'
