steps:
  # Step 1: Wait before build
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Waiting before running the build phase..."
        sleep 10

  # Step 2: Install ffmpeg, dependencies, and run annotation script
  - name: 'python:3.8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd annotation-pipeline
        apt-get update -y
        apt-get install -y ffmpeg libsm6 libxext6 libxrender-dev libgomp1 -qq || echo "Package installation completed"
        pip install -r requirements.txt
        python3 annotations.py

  # Step 3: Check and upload artifacts manually
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd annotation-pipeline
        
        echo "=== Directory Contents ==="
        echo "Frames directory:"
        ls -lah frames/ || echo "Empty"
        echo ""
        echo "Predict directory:"
        ls -lah predict/ || echo "Empty"
        echo ""
        
        # Upload files if they exist
        if [ -f "inspection.csv" ]; then
          echo "Uploading inspection.csv..."
          gsutil cp inspection.csv gs://annotations123/artifacts/${BUILD_ID}/
        fi
        
        if [ "$(ls -A frames 2>/dev/null)" ]; then
          echo "Uploading frames..."
          gsutil -m cp -r frames/* gs://annotations123/artifacts/${BUILD_ID}/frames/
        else
          echo "No frames to upload"
        fi
        
        if [ "$(ls -A predict 2>/dev/null)" ]; then
          echo "Uploading predictions..."
          gsutil -m cp -r predict/* gs://annotations123/artifacts/${BUILD_ID}/predict/
        else
          echo "No predictions to upload"
        fi
        
        echo "Artifact upload completed!"

# Timeout for the build
timeout: '1800s'

# Options
options:
  logging: CLOUD_LOGGING_ONLY


